name: on-release

on:
  push:
    tags:
      - "v*.*.*"

defaults:
  run:
    shell: bash

jobs:
  build_and_test:
    permissions: write-all
    name: >
      Build and test a usbman on ${{ matrix.os }}.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, macos-15-intel macos-15]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run the projects setup.
        run: |
          pip3 install pipenv 
          pipenv sync --python /bin/python3

      - name: Add msbuild to PATH
        if: ${{ matrix.os == 'windows-latest' }}
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build
        run: |
          pipenv run ./package_usbman
          mv dist/usbman.tar.gz usbman-${{ matrix.os }}.tar.gz

      - name: Minimaly test
        run: dist/usbman/usbman --help

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: usbman-${{ matrix.os }}.tar.gz