name: on-release

on:
  push:
    tags:
      - "v*.*.*"

defaults:
  run:
    shell: bash

jobs:
  build_and_test:
    permissions: write-all

    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'App'
            platform:  'linux/amd64'
            os: 'ubuntu-22.04'
          - name: 'App'
            platform:  'linux/amd64'
            os: 'ubuntu-24.04'
          - name: 'App'
            platform:  'darwin/universal'
            os: 'macos-15'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: setup generic
        if: ${{ matrix.build.os != 'macos-15' }}
        run: |
          pip3 install pipenv 
          pipenv sync --python /bin/python3

      - name: setup macos
        if: ${{ matrix.build.os == 'macos-15' }}
        run: |
          pip3 install --break-system-packages pipenv 
          pipenv sync --python /bin/python3

      - name: Add msbuild to PATH
        if: ${{ matrix.build.os == 'windows-latest' }}
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build
        run: |
          pipenv run ./package_usbman
          mv dist/usbman.tar.gz usbman-${{ matrix.build.os }}-${{ matrix.build.platform }}.tar.gz

      - name: Minimaly test
        run: dist/usbman/usbman --help

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: usbman-${{ matrix.build.os }}-${{ matrix.build.platform }}.tar.gz