name: on-release

on:
  push:
    tags:
      - "v*.*.*"

defaults:
  run:
    shell: bash

jobs:
  build:
    permissions: write-all

    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'usbman'
            platform:  'linux/amd64'
            os: 'ubuntu-22.04'
          - name: 'usbman'
            platform:  'linux/amd64'
            os: 'ubuntu-24.04'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: setup generic
        if: ${{ matrix.build.os != 'macos-15' }}
        run: |
          pip3 install pipenv 
          pipenv sync --python /bin/python3

      - name: setup macos
        if: ${{ matrix.build.os == 'macos-15' }}
        run: |
          pip3 install --break-system-packages pipenv 
          pipenv sync

      - name: Add msbuild to PATH
        if: ${{ matrix.build.os == 'windows-latest' }}
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build
        run: |
          pipenv run ./package_usbman

      - name: Minimaly test
        run: dist/usbman/usbman --help

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: usbman-${{ matrix.build.os }}-amd64.tar.gz
          path: dist/usbman.tar.gz

  # release:
  #   permissions: write-all
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download Artifacts
  #       uses: actions/download-artifact@v4
  #     - name: info  
  #       run: |
  #         pwd
  #         echo $GITHUB_WORKSPACE
  #         ls -la
  #         ls -R
  #     - name: Create GitHub Release
  #       uses: softprops/action-gh-release@v2
  #       with:
  #         files: |
  #           usbman-ubuntu-22.04-amd64.tar.gz
  #           usbman-ubuntu-24.04-amd64.tar.gz

  create_release:
    needs: build
    name: Create release
    runs-on: ubuntu-latest
    # Note this. We are going to use that in further jobs.
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  release_assets:
    name: Release assets
    needs: create_release # we need to know the upload URL
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
      - name: info  
        run: |
          pwd
          echo $GITHUB_WORKSPACE
          ls -la
          ls -R
      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          # This is how it will be named on the release page. Put hatever name
          # you like, remember that they need to be different for each platform.
          # You can choose any build matrix parameters. For Rust I use the
          # target triple.
          asset_name: usbman-ubuntu-24.04-amd64.tar.gz
          # The path to the file you want to upload.
          asset_path: usbman-ubuntu-24.04-amd64.tar.gz
          # probably you will need to change it, but most likely you are
          # uploading a binary file
          asset_content_type: application/octet-stream
      - name: Upload release assets 2
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          # This is how it will be named on the release page. Put hatever name
          # you like, remember that they need to be different for each platform.
          # You can choose any build matrix parameters. For Rust I use the
          # target triple.
          asset_name: usbman-ubuntu-22.04-amd64.tar.gz
          # The path to the file you want to upload.
          asset_path: usbman-ubuntu-22.04-amd64.tar.gz
          # probably you will need to change it, but most likely you are
          # uploading a binary file
          asset_content_type: application/octet-stream