name: on-release

on:
  push:
    tags:
      - "v*.*.*"

defaults:
  run:
    shell: bash

jobs:
  build:
    permissions: write-all

    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'App'
            platform:  'linux/amd64'
            os: 'ubuntu-22.04'
          - name: 'App'
            platform:  'linux/amd64'
            os: 'ubuntu-24.04'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: setup generic
        if: ${{ matrix.build.os != 'macos-15' }}
        run: |
          pip3 install pipenv 
          pipenv sync --python /bin/python3

      - name: setup macos
        if: ${{ matrix.build.os == 'macos-15' }}
        run: |
          pip3 install --break-system-packages pipenv 
          pipenv sync

      - name: Add msbuild to PATH
        if: ${{ matrix.build.os == 'windows-latest' }}
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build
        run: |
          pipenv run ./package_usbman

      - name: Minimaly test
        run: dist/usbman/usbman --help

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: usbman-${{ matrix.build.os }}-amd64.tar.gz
          path: dist/usbman.tar.gz

  release:
    permissions: write-all
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: usbman/usbman-*.tar.gz