name: on-release

on:
  push:
    tags:
      - "v*.*.*"

defaults:
  run:
    shell: bash

jobs:
  build:
    permissions: write-all

    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'usbman'
            platform:  'ubuntu-22.04-amd64'
            os: 'ubuntu-22.04'
          - name: 'usbman'
            platform:  'ubuntu-24.04-amd64'
            os: 'ubuntu-24.04'
#          - name: 'usbman'
#            platform:  'macos-15-intel'
#            os: 'macos-15-intel'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: setup generic
        if: ${{ matrix.build.os != 'macos-15-intel' }}
        run: |
          pip3 install pipenv 
          pipenv sync --python /bin/python3

      - name: setup macos
        if: ${{ matrix.build.os == 'macos-15-intel' }}
        run: |
          pip3 install --break-system-packages pipenv 
          pipenv sync --python /usr/local/bin/python3

      - name: Add msbuild to PATH
        if: ${{ matrix.build.os == 'windows-latest' }}
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build
        run: |
          pipenv run ./package_usbman
          mv dist/usbman.tar.gz usbman-${{ matrix.build.platform }}.tar.gz

      - name: Minimaly test
        run: dist/usbman/usbman --help

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: usbman-${{ matrix.build.platform }}
          path: usbman-${{ matrix.build.platform }}.tar.gz

  release:
    permissions: write-all
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
      - name: info  
        run: |
          pwd
          echo $GITHUB_WORKSPACE
          ls -la
          ls -R
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            usbman-ubuntu-22.04-amd64/*
            usbman-ubuntu-24.04-amd64/*
#            usbman-macos-15-intel/*
